INSERT INTO AUTOR (NOMBRE, PAISDEORIGEN) VALUES ('Gabriel Garcia Marquez', 'Colombia');
INSERT INTO AUTOR (NOMBRE, PAISDEORIGEN) VALUES ('J.K. Rowling', 'Reino Unido');
INSERT INTO AUTOR (NOMBRE, PAISDEORIGEN) VALUES ('Haruki Murakami', 'Japon');

INSERT INTO LIBRO (CATEGORIA, FECHA_PUBLICACION, ISBN, TITULO, AUTOR_ID) VALUES ('Realismo magico', '1967-05-30', '1234567890', 'Cien Anos de Soledad', 1);
INSERT INTO LIBRO (CATEGORIA, FECHA_PUBLICACION, ISBN, TITULO, AUTOR_ID) VALUES ('Fantasia', '1997-06-26', '0987654321', 'Harry Potter y la Piedra Filosofal', 2);
INSERT INTO LIBRO (CATEGORIA, FECHA_PUBLICACION, ISBN, TITULO, AUTOR_ID) VALUES ('Ficcion', '2002-09-12', '1122334455', 'Kafka en la Orilla', 3);
