spring.application.name=dgt-api

# Conexión a la BBDD local (asegúrate de que en Compass la llamaste 'dgt_db')
spring.data.mongodb.uri=mongodb://localhost:27017/dgt_db


# Esto muestra las peticiones HTTP en la consola (útil para depurar)
logging.level.org.springframework.web=DEBUG