// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBBHqIj-raYAvgF_yMKCk_WgfVgFTmri60',
    appId: '1:583125018644:android:85742d26d37e1e68e11f01',
    messagingSenderId: '583125018644',
    projectId: 'fireflutterdam-6bd97',
    storageBucket: 'fireflutterdam-6bd97.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB7AW3i1ASKdbPga8cz70YlPTE5UqwDi3g',
    appId: '1:583125018644:ios:dc96698940712a8be11f01',
    messagingSenderId: '583125018644',
    projectId: 'fireflutterdam-6bd97',
    storageBucket: 'fireflutterdam-6bd97.firebasestorage.app',
    androidClientId: '583125018644-ff91iogmvbfavd1o55fucnagvinjeiq0.apps.googleusercontent.com',
    iosClientId: '583125018644-aeq4aaaph5tks0f2sc14svnphh66k6no.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebaseApp',
  );

}